#!/bin/sh
# postinst script for noisebridge-api

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
      echo "chown'ing application files"
      chown -R www-data:www-data /usr/lib/noisebridge-api
      echo "Enabling the \"noisebridge-api\" apache site"
      /usr/sbin/a2ensite noisebridge-api
      echo "Ensuring that the \"wsgi\" apache module is running"
      /usr/sbin/a2enmod wsgi
      echo "Ensuring that the \"headers\" apache module is running"
      /usr/sbin/a2enmod headers
      echo "Gracefulling apache."
      echo "NOTE: You may still need to restart apache to load wsgi"
      /usr/sbin/apache2ctl graceful
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
